name: PHP Native CI/CD Workflow

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur la branche principale
  pull_request:
    branches:
      - main  # Exécute le workflow lors d'une pull request sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu fournie par GitHub

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root  # Mot de passe root
          MYSQL_DATABASE: testdb  # Base de données test
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"  # Vérifie la santé de MySQL

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2  # Clone le code de votre dépôt GitHub

      # Étape 2 : Configurer PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.13'  # Version PHP à utiliser
          extensions: mysqli  # Active l'extension mysqli nécessaire pour la connexion à MySQL

      # Étape 3 : Vérification de la syntaxe PHP
      - name: Check PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \;  # Vérifie la syntaxe de tous les fichiers PHP

      # Étape 4 : Tester la connexion MySQL
      - name: Test MySQL connection
        run: |
          echo "Waiting for MySQL to be ready..."
          # Attente courte pour MySQL
          timeout=30  # Délai d'attente de 30 secondes
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."
            sleep 2
            ((timeout--))
            if [ $timeout -le 0 ]; then
              echo "MySQL didn't start in time, exiting"
              exit 1  # Échoue si MySQL ne démarre pas dans le délai
            fi
          done
          echo "MySQL is ready!"
          echo "Testing MySQL connection..."
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"  # Liste les bases de données
