name: PHP Native CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

env:
  RESOURCE-GROUP: agenda-mysql
  LOCATION: Central US
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: bf182e9b-9eda-46c1-882a-3c5668f297ff
  WEBAPP-NAME: agenda-app-akfhgecxbdecc7a8.centralus-01.azurewebsites.net

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Ubuntu runner provided by GitHub

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure using the Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mysqli

      # Step 4: Syntax check for PHP files
      - name: Check PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \;

      # Step 5: Deploy App Service Plan
      - name: Deploy App Service Plan
        run: |
          az deployment group create \
          --resource-group ${{ env.RESOURCE-GROUP }} \
          --template-file ./infra/appserviceplan.bicep \
          --parameters location="${{ env.LOCATION }}"

      # Step 6: Deploy MySQL Database
      - name: Deploy MySQL Database
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file ./infra/mysql.bicep \
            --parameters location="${{ env.LOCATION }}"
      
      # Step 7: Deploy Web App
      - name: Deploy Web App
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file ./infra/webapp.bicep \
            --parameters location="${{ env.LOCATION }}"


      # Step 8: Deploy Outputs (Optional)
      - name: Deploy Outputs
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file ./infra/output.bicep

      # Step 9: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
