name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushes dans la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mysqli

      # Étape 3 : Vérification de la syntaxe PHP
      - name: Check PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \;

      # Étape 4 : Déployer sur Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-php-app'  # Remplacez par le nom de votre App Service
          slot-name: 'production' # Nom de l'environnement (production par défaut)
          publish-profile: ${ AZURE_WEBAPP_PUBLISH_PROFILE }  # Profil de publication sécurisé
