name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déploiement automatique lors de chaque push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Construire le projet (si nécessaire)
      - name: Build Project
        run: |
          mkdir -p build
          cp -r * build/  # Copie tous les fichiers du projet dans le répertoire build

      # Étape 3 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Branche de déploiement sur GitHub Pages
          folder: build     # Le répertoire contenant les fichiers à déployer
